#!/usr/bin/env node
/**
 * scripts/healthcheck.js
 * Tokenfly SRE — Synthetic Health Check
 * Author: Liam (SRE)
 *
 * Polls GET /api/health every 30 seconds.
 * Evaluates response time and status against SLO thresholds.
 * Writes results to public/reports/health_check_log.jsonl
 * Writes active alerts to public/reports/active_alerts.md
 *
 * Usage:
 *   node scripts/healthcheck.js [--port 3199] [--interval 30]
 *   node scripts/healthcheck.js --once    # Run once and exit (useful for scripts)
 *
 * Alert thresholds (from sre_plan.md):
 *   ALT-001: /api/health returns non-200 for > 30s  → P0 Critical
 *   ALT-002: p99 latency > 500ms for 5 min           → P1 High
 *   ALT-009: heapUsed/heapTotal > 85% sustained 3 checks AND heapTotal > 50MB → P1 High
 */

'use strict';

const http = require('http');
const fs = require('fs');
const path = require('path');

// ── Configuration ──────────────────────────────────────────────────────────────

const args = process.argv.slice(2);
const portIdx = args.indexOf('--port');
const intervalIdx = args.indexOf('--interval');
const runOnce = args.includes('--once');

const PORT = portIdx >= 0 ? parseInt(args[portIdx + 1], 10) : 3100;
const INTERVAL_MS = intervalIdx >= 0 ? parseInt(args[intervalIdx + 1], 10) * 1000 : 30_000;
const BASE_DIR = path.resolve(__dirname, '..');
const API_KEY = process.env.API_KEY || '';

const HEALTH_URL = `http://localhost:${PORT}/api/health`;
const LOG_FILE = path.join(BASE_DIR, 'public', 'reports', 'health_check_log.jsonl');
const ALERTS_FILE = path.join(BASE_DIR, 'public', 'reports', 'active_alerts.md');

const THRESHOLDS = {
  response_time_p99_ms: 500,   // ALT-002
  heap_used_max_pct: 0.85,      // ALT-009 ratio threshold
  heap_min_total_mb: 50,        // ALT-009 only fires if heapTotal > 50MB (avoids V8 small-heap false positives)
  heap_sustained_count: 3,      // ALT-009 requires N consecutive samples above threshold
  timeout_ms: 5000,
};

// In-memory ring buffer for latency percentile tracking (last 10 samples)
const latencySamples = [];
const MAX_SAMPLES = 10;

// Track consecutive failures for ALT-001
let consecutiveFailures = 0;
const FAILURE_THRESHOLD_COUNT = 1; // Any failure = alert (30s poll, so 1 failure = 30s down)

// ALT-009 sustained heap tracking
let consecutiveHeapBreaches = 0;

// ── Utility ────────────────────────────────────────────────────────────────────

function percentile(sorted, p) {
  if (sorted.length === 0) return 0;
  const idx = Math.ceil((p / 100) * sorted.length) - 1;
  return sorted[Math.max(0, idx)];
}

function isoNow() {
  return new Date().toISOString();
}

function appendLog(entry) {
  try {
    fs.appendFileSync(LOG_FILE, JSON.stringify(entry) + '\n');
  } catch (err) {
    console.error(`[healthcheck] Failed to write log: ${err.message}`);
  }
}

// ── Alert Management ───────────────────────────────────────────────────────────

const activeAlerts = new Map(); // alertId → { severity, message, triggeredAt }

function fireAlert(alertId, severity, message) {
  if (!activeAlerts.has(alertId)) {
    console.error(`[ALERT ${severity}] ${alertId}: ${message}`);
    activeAlerts.set(alertId, { severity, message, triggeredAt: isoNow() });
    writeAlertsFile();
  }
}

function clearAlert(alertId) {
  if (activeAlerts.has(alertId)) {
    console.log(`[RESOLVED] ${alertId} cleared`);
    activeAlerts.delete(alertId);
    writeAlertsFile();
  }
}

function writeAlertsFile() {
  const lines = [
    '# Active Alerts',
    `_Last updated: ${isoNow()}_`,
    '',
  ];

  if (activeAlerts.size === 0) {
    lines.push('**No active alerts. All systems nominal.**');
  } else {
    lines.push(`**${activeAlerts.size} active alert(s)**`);
    lines.push('');
    lines.push('| Alert ID | Severity | Message | Triggered At |');
    lines.push('|----------|----------|---------|--------------|');
    for (const [id, alert] of activeAlerts) {
      lines.push(`| ${id} | ${alert.severity} | ${alert.message} | ${alert.triggeredAt} |`);
    }
  }

  lines.push('');
  lines.push('---');
  lines.push('_Generated by scripts/healthcheck.js_');

  try {
    fs.writeFileSync(ALERTS_FILE, lines.join('\n') + '\n');
  } catch (err) {
    console.error(`[healthcheck] Failed to write alerts file: ${err.message}`);
  }
}

// ── HTTP Health Check ──────────────────────────────────────────────────────────

function checkHealth() {
  const startMs = Date.now();

  const reqOptions = { timeout: THRESHOLDS.timeout_ms };
  if (API_KEY) reqOptions.headers = { Authorization: `Bearer ${API_KEY}` };

  const req = http.get(HEALTH_URL, reqOptions, (res) => {
    let body = '';
    res.on('data', (chunk) => { body += chunk; });
    res.on('end', () => {
      const durationMs = Date.now() - startMs;
      const statusCode = res.statusCode;
      const timestamp = isoNow();

      let parsed = null;
      let parseError = null;
      try {
        parsed = JSON.parse(body);
      } catch (e) {
        parseError = e.message;
      }

      // ── Latency tracking ──
      latencySamples.push(durationMs);
      if (latencySamples.length > MAX_SAMPLES) latencySamples.shift();
      const sorted = [...latencySamples].sort((a, b) => a - b);
      const p99 = percentile(sorted, 99);
      const p50 = percentile(sorted, 50);

      // ── Build log entry ──
      const entry = {
        timestamp,
        status_code: statusCode,
        duration_ms: durationMs,
        p50_ms: p50,
        p99_ms: p99,
        heap_used: parsed?.memory?.heapUsed ?? null,
        heap_total: parsed?.memory?.heapTotal ?? null,
        active_agents: parsed?.activeAgents ?? null,
        sse_clients: parsed?.sseClients ?? null,
        uptime_ms: parsed?.uptime_ms ?? null,
        alerts_fired: [],
      };

      // ── ALT-001: Non-200 response ──
      if (statusCode !== 200 || parseError) {
        consecutiveFailures++;
        const msg = parseError
          ? `Parse error after ${durationMs}ms: ${parseError}`
          : `HTTP ${statusCode} after ${durationMs}ms`;
        fireAlert('ALT-001', 'P0-Critical', msg);
        entry.alerts_fired.push('ALT-001');
      } else {
        consecutiveFailures = 0;
        clearAlert('ALT-001');
      }

      // ── ALT-002: p99 latency > 500ms ──
      if (p99 > THRESHOLDS.response_time_p99_ms) {
        fireAlert('ALT-002', 'P1-High', `p99 latency ${p99}ms > ${THRESHOLDS.response_time_p99_ms}ms threshold`);
        entry.alerts_fired.push('ALT-002');
      } else if (latencySamples.length >= 3) {
        clearAlert('ALT-002');
      }

      // ── ALT-009: Heap saturation > 85% (sustained, with minimum heap size gate) ──
      // V8 starts with a tiny heap (~8MB) and heapUsed/heapTotal is nearly always >85%
      // on small processes. Only alert if heapTotal > 50MB (real saturation) AND
      // sustained for N consecutive checks (avoids transient GC spikes).
      if (parsed?.memory?.heapTotal > 0) {
        const heapTotalMb = parsed.memory.heapTotal / (1024 * 1024);
        const heapPct = parsed.memory.heapUsed / parsed.memory.heapTotal;
        const isRealHeap = heapTotalMb >= THRESHOLDS.heap_min_total_mb;
        const isHighPct = heapPct > THRESHOLDS.heap_used_max_pct;

        if (isRealHeap && isHighPct) {
          consecutiveHeapBreaches++;
          if (consecutiveHeapBreaches >= THRESHOLDS.heap_sustained_count) {
            fireAlert('ALT-009', 'P1-High',
              `Heap ${(heapPct * 100).toFixed(1)}% used (${Math.round(parsed.memory.heapUsed / 1024 / 1024)}MB / ${Math.round(heapTotalMb)}MB) sustained ${consecutiveHeapBreaches} checks`);
            entry.alerts_fired.push('ALT-009');
          }
        } else {
          consecutiveHeapBreaches = 0;
          clearAlert('ALT-009');
        }
      }

      appendLog(entry);
      const statusIcon = entry.alerts_fired.length > 0 ? '⚠' : '✓';
      console.log(`[healthcheck] ${statusIcon} ${timestamp} HTTP ${statusCode} ${durationMs}ms p99=${p99}ms agents=${entry.active_agents ?? '?'}`);

      if (runOnce) process.exit(0);
    });
  });

  req.on('timeout', () => {
    req.destroy();
    const durationMs = Date.now() - startMs;
    consecutiveFailures++;
    fireAlert('ALT-001', 'P0-Critical', `Timeout after ${durationMs}ms (threshold: ${THRESHOLDS.timeout_ms}ms)`);
    const entry = {
      timestamp: isoNow(),
      status_code: null,
      duration_ms: durationMs,
      error: 'timeout',
      alerts_fired: ['ALT-001'],
    };
    appendLog(entry);
    console.error(`[healthcheck] TIMEOUT after ${durationMs}ms`);
    if (runOnce) process.exit(1);
  });

  req.on('error', (err) => {
    const durationMs = Date.now() - startMs;
    consecutiveFailures++;
    fireAlert('ALT-001', 'P0-Critical', `Connection error: ${err.message}`);
    const entry = {
      timestamp: isoNow(),
      status_code: null,
      duration_ms: durationMs,
      error: err.message,
      alerts_fired: ['ALT-001'],
    };
    appendLog(entry);
    console.error(`[healthcheck] ERROR: ${err.message}`);
    if (runOnce) process.exit(1);
  });
}

// ── Main ───────────────────────────────────────────────────────────────────────

// Ensure output directories exist
fs.mkdirSync(path.dirname(LOG_FILE), { recursive: true });

// Write initial clear alerts file
writeAlertsFile();

console.log(`[healthcheck] Starting — polling ${HEALTH_URL} every ${INTERVAL_MS / 1000}s`);
console.log(`[healthcheck] Log → ${LOG_FILE}`);
console.log(`[healthcheck] Alerts → ${ALERTS_FILE}`);

// Run immediately, then on interval
checkHealth();

if (!runOnce) {
  setInterval(checkHealth, INTERVAL_MS);
}
