-- Kalshi Trading Strategy Framework Schema
-- Author: Bob (Backend Engineer)
-- Task: #220 — Strategy framework (signals + position sizing + P&L tracking)

-- ---------------------------------------------------------------------------
-- Strategies Table
-- Defines automated trading strategies
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS strategies (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    
    -- Strategy metadata
    name VARCHAR(100) NOT NULL,
    description TEXT,
    strategy_type VARCHAR(50) NOT NULL, -- 'mean_reversion', 'momentum', 'arbitrage', etc.
    
    -- Configuration (stored as JSON for flexibility)
    config JSONB NOT NULL DEFAULT '{}',
    
    -- Status
    status VARCHAR(20) NOT NULL DEFAULT 'stopped', -- stopped, active, paused
    
    -- Risk parameters
    max_position_size INTEGER DEFAULT 1000, -- max contracts per position
    max_daily_loss INTEGER DEFAULT 50000, -- max daily loss in cents ($500)
    max_exposure INTEGER DEFAULT 200000, -- max total exposure in cents ($2000)
    
    -- Performance summary (denormalized for quick reads)
    total_trades INTEGER DEFAULT 0,
    winning_trades INTEGER DEFAULT 0,
    losing_trades INTEGER DEFAULT 0,
    total_pnl INTEGER DEFAULT 0, -- in cents
    
    -- Timestamps
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    activated_at TIMESTAMP WITH TIME ZONE,
    stopped_at TIMESTAMP WITH TIME ZONE,
    
    CONSTRAINT valid_strategy_status CHECK (status IN ('stopped', 'active', 'paused'))
);

CREATE INDEX IF NOT EXISTS idx_strategies_status ON strategies(status);
CREATE INDEX IF NOT EXISTS idx_strategies_type ON strategies(strategy_type);

-- ---------------------------------------------------------------------------
-- Strategy Signals Table
-- Records signals generated by strategies
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS strategy_signals (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    strategy_id UUID NOT NULL REFERENCES strategies(id) ON DELETE CASCADE,
    market_id UUID NOT NULL REFERENCES markets(id) ON DELETE CASCADE,
    
    -- Signal details
    side VARCHAR(10) NOT NULL, -- 'yes' or 'no'
    signal_type VARCHAR(20) NOT NULL, -- 'entry', 'exit', 'hold'
    confidence DECIMAL(4,3) NOT NULL CHECK (confidence >= 0 AND confidence <= 1),
    
    -- Pricing context
    target_price INTEGER, -- suggested entry price in cents
    current_price INTEGER, -- price when signal was generated
    expected_edge INTEGER, -- expected edge in cents
    
    -- Sizing recommendation
    recommended_contracts INTEGER,
    
    -- Result tracking
    acted_on BOOLEAN DEFAULT FALSE,
    order_id UUID REFERENCES orders(id),
    result_pnl INTEGER, -- actual P&L if acted upon
    
    -- Timestamps
    generated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    expired_at TIMESTAMP WITH TIME ZONE, -- when signal is no longer valid
    
    CONSTRAINT valid_signal_side CHECK (side IN ('yes', 'no')),
    CONSTRAINT valid_signal_type CHECK (signal_type IN ('entry', 'exit', 'hold'))
);

CREATE INDEX IF NOT EXISTS idx_strategy_signals_strategy ON strategy_signals(strategy_id);
CREATE INDEX IF NOT EXISTS idx_strategy_signals_market ON strategy_signals(market_id);
CREATE INDEX IF NOT EXISTS idx_strategy_signals_generated ON strategy_signals(generated_at);
CREATE INDEX IF NOT EXISTS idx_strategy_signals_actedd_on ON strategy_signals(acted_on);

-- ---------------------------------------------------------------------------
-- Strategy Trades Table
-- Links trades/orders to strategies for P&L attribution
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS strategy_trades (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    strategy_id UUID NOT NULL REFERENCES strategies(id) ON DELETE CASCADE,
    order_id UUID NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    trade_id UUID REFERENCES trades(id) ON DELETE SET NULL,
    signal_id UUID REFERENCES strategy_signals(id) ON DELETE SET NULL,
    
    -- Attribution
    attribution_type VARCHAR(20) DEFAULT 'full', -- 'full', 'partial'
    attributed_contracts INTEGER NOT NULL,
    attributed_pnl INTEGER, -- in cents
    
    recorded_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    
    UNIQUE(strategy_id, order_id)
);

CREATE INDEX IF NOT EXISTS idx_strategy_trades_strategy ON strategy_trades(strategy_id);
CREATE INDEX IF NOT EXISTS idx_strategy_trades_order ON strategy_trades(order_id);
CREATE INDEX IF NOT EXISTS idx_strategy_trades_recorded ON strategy_trades(recorded_at);

-- ---------------------------------------------------------------------------
-- Strategy Performance Snapshots Table
-- Daily/hourly performance tracking per strategy
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS strategy_performance (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    strategy_id UUID NOT NULL REFERENCES strategies(id) ON DELETE CASCADE,
    
    -- Period
    period VARCHAR(10) NOT NULL, -- 'hourly', 'daily', 'weekly'
    period_start TIMESTAMP WITH TIME ZONE NOT NULL,
    
    -- Trading activity
    trades_count INTEGER DEFAULT 0,
    contracts_traded INTEGER DEFAULT 0,
    
    -- P&L (in cents)
    realized_pnl INTEGER DEFAULT 0,
    unrealized_pnl INTEGER DEFAULT 0,
    total_pnl INTEGER DEFAULT 0,
    
    -- Exposure
    max_exposure INTEGER DEFAULT 0,
    avg_exposure INTEGER DEFAULT 0,
    ending_exposure INTEGER DEFAULT 0,
    
    -- Risk metrics
    max_drawdown INTEGER DEFAULT 0, -- peak to trough in cents
    sharpe_ratio DECIMAL(10,4),
    win_rate DECIMAL(5,4),
    
    -- Cumulative
    cumulative_pnl INTEGER DEFAULT 0,
    
    -- Unique constraint
    UNIQUE(strategy_id, period, period_start)
);

CREATE INDEX IF NOT EXISTS idx_strategy_performance_strategy ON strategy_performance(strategy_id);
CREATE INDEX IF NOT EXISTS idx_strategy_performance_period ON strategy_performance(period, period_start);

-- ---------------------------------------------------------------------------
-- Strategy Positions View
-- Open positions attributed to strategies
-- ---------------------------------------------------------------------------
CREATE OR REPLACE VIEW strategy_positions_view AS
SELECT 
    st.strategy_id,
    s.name as strategy_name,
    p.*,
    m.ticker,
    m.title as market_title,
    opwm.current_yes_price,
    opwm.current_no_price,
    opwm.calculated_unrealized_pnl
FROM strategy_trades st
JOIN strategies s ON st.strategy_id = s.id
JOIN orders o ON st.order_id = o.id
JOIN positions p ON o.market_id = p.market_id
JOIN markets m ON p.market_id = m.id
LEFT JOIN open_positions_with_markets opwm ON p.id = opwm.id
WHERE p.status = 'open';

-- ---------------------------------------------------------------------------
-- Strategy Summary View
-- Quick overview of all strategies with latest metrics
-- ---------------------------------------------------------------------------
CREATE OR REPLACE VIEW strategy_summary_view AS
SELECT 
    s.id,
    s.name,
    s.description,
    s.strategy_type,
    s.status,
    s.total_trades,
    s.winning_trades,
    s.losing_trades,
    s.total_pnl,
    CASE 
        WHEN s.total_trades > 0 THEN s.winning_trades::DECIMAL / s.total_trades
        ELSE 0
    END as win_rate,
    COALESCE(sp.signal_strength, 0) as signal_strength,
    COALESCE(td.trades_today, 0) as trades_today,
    s.created_at,
    s.activated_at,
    s.updated_at
FROM strategies s
LEFT JOIN (
    SELECT strategy_id, COUNT(*) as trades_today
    FROM strategy_trades
    WHERE recorded_at >= CURRENT_DATE
    GROUP BY strategy_id
) td ON s.id = td.strategy_id
LEFT JOIN (
    SELECT strategy_id, AVG(confidence) as signal_strength
    FROM strategy_signals
    WHERE generated_at >= NOW() - INTERVAL '24 hours'
      AND acted_on = FALSE
    GROUP BY strategy_id
) sp ON s.id = sp.strategy_id;

-- ---------------------------------------------------------------------------
-- Trigger for updated_at on strategies
-- ---------------------------------------------------------------------------
DROP TRIGGER IF EXISTS update_strategies_updated_at ON strategies;
CREATE TRIGGER update_strategies_updated_at
    BEFORE UPDATE ON strategies
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- ---------------------------------------------------------------------------
-- Comments
-- ---------------------------------------------------------------------------
COMMENT ON TABLE strategies IS 'Trading strategy definitions';
COMMENT ON TABLE strategy_signals IS 'Signals generated by strategies';
COMMENT ON TABLE strategy_trades IS 'Trade attribution to strategies';
COMMENT ON TABLE strategy_performance IS 'Periodic performance snapshots per strategy';
